### ISSUE TITLE
TypeError: onResult is not a function

### ISSUE THREAD

**Issue by margau** [melle/l33tport#7]
In the new-login branch it says:

l33tport.js:105
            onResult(res.statusCode, output);
            ^

TypeError: onResult is not a function
    at IncomingMessage.<anonymous> (/var/monitoring/l33tport/l33tport.js:105:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Currently i try to find the problem but not found it yet.

**Comment by hensur** [comment]
Should be fixed by #8
